modLoader="javafml"
loaderVersion="[47,)"
license="Creative Commons Attribution-NonCommercial 3.0"

[[mods]]
modId="quasimod"
version="1.0.0"
displayName="quasimod"
displayURL="https://mcreator.net"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="flo8903, zombiegmbh, asda9376, MCreator"

[[dependencies.quasimod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"



[[dependencies.quasimod]]
    modId="curios_api"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.quasimod]]
    modId="geckolib"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"

